[package]
name = "cybersub"
version = "0.1.0"
authors = ["Andrei Vasiliu <whyte.vuhuni@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = "0.13.0" # Gives us egui, epi and web+native backends

[profile.release]
opt-level = 2 # fast and small wasm

[patch.crates-io]
